# Earthshaker Theme - Blooming Forest Edition

background        #1a1c1b
foreground        #e0d6c3
selection_background #2c302c
selection_foreground #e0d6c3

cursor            #ff9933
cursor_text_color #1a1c1b

# Normal colors
color0   #1a1c1b  
color1   #ff6655 
color2   #90b48f
color3   #eabf6a  
color4   #809775 
color5   #f28b50
color6   #6c8f6c  
color7   #e0d6c3 

# Bright colors
color8   #444844  
color9   #ff6655 
color10  #90b48f
color11  #ffc07c  
color12  #acc196 
color13  #d68e5d
color14  #a3b18a  
color15  #f5e9d7 

# Tab bar / Borders
active_tab_background   #2c302c
active_tab_foreground   #e0d6c3
inactive_tab_background #1a1c1b
inactive_tab_foreground #7c8474
tab_bar_background      #1a1c1b

# Other window parts
selection_background #2c302c
selection_foreground #e0d6c3
